import {
  Briefcase,
  Cloud,
  Code,
  Code2,
  Coffee,
  Cpu,
  Database,
  GitBranch,
  Globe,
  GraduationCap,
  Layers,
  Layout,
  Mail,
  MapPin,
  Palette,
  Phone,
  Server,
  Smartphone,
  Terminal,
} from "lucide-react";

import { FaGithub, FaLinkedinIn } from "react-icons/fa6";

export const stats = [
  { label: "Doświadczenia zawodowego", value: "3+" },
  { label: "Ukończonych projektów", value: "40+" },
  { label: "Stworzonych komponentów UI", value: "50+" },
  { label: "Technologi w praktyce", value: "20+" },
];

export const highlights = [
  { icon: MapPin, text: "Kraków, Polska/Zdalnie" },
  { icon: Briefcase, text: "Dostępna do nowych projektów" },
  {
    icon: GraduationCap,
    text: "3+ lata praktyki w tworzeniu interfejsów webowych",
  },
  { icon: Code, text: "Kod i ciekawość technologii" },
];

export const userReviewData = [
  {
    id: 1,
    name: "John Doe",
    profession: "Real Estate Agent",
    userImage: "/images/u1.jpg",
    review:
      "A wonderful experience! The platform made it easy to find exactly what I needed. lorem ipsum dolor sit ame",
  },
  {
    id: 2,
    name: "Mike Smith",
    profession: "Business Owner",
    userImage: "/images/u2.jpg",
    review:
      "Great selection of properties and seamless process. Highly recommended for anyone looking to invest.",
  },
  {
    id: 3,
    name: "Alex Johnson",
    profession: "Web developer",
    userImage: "/images/u3.jpg",
    review:
      "The website helped me find my dream home quickly and hassle-free. Exceptional service!",
  },
  {
    id: 4,
    name: "Emily Clark",
    profession: "Interior Designer",
    userImage: "/images/u4.jpg",
    review:
      "Fantastic range of properties with clear details. The best platform for home and design inspiration!",
  },
];

export const contactInfo = [
  {
    icon: Mail,
    label: "Email",
    value: "amanda.chawinska@spoko.pl",
    href: "mailto:amanda.chawinska@spoko.pl",
  },
  {
    icon: Phone,
    label: "Telefon",
    value: "500688117",
    href: "tel:500688117",
  },
  {
    icon: MapPin,
    label: "Lokalizacja",
    value: "Kraków, Polska",
  },
];

export const socialLinks = [
  {
    icon: FaGithub,
    href: "https://github.com/AmandaChawinska",
    label: "GitHub",
  },
  {
    icon: FaLinkedinIn,
    href: "https://pl.linkedin.com/in/amanda-chawi%C5%84ska-frontend-developer",
    label: "LinkedIn",
  },
];

export const experiences = [
  {
    type: "work",
    title: "Frontend Developer",
    company: "GQ Group",
    period: "2022 - Present",
    description:
      "Tworzenie modularnych i responsywnych interfejsów na podstawie projektów UX/UI. Rozwój oraz refaktoryzacja dedykowanych motywów WordPress, implementacja dynamicznych funkcjonalności w JavaScript oraz integracja CMS z warstwą frontendową. Optymalizacja wydajności, code review oraz współpraca z zespołem projektowym (UX/UI, PM).",
    technologies: [
      "JavaScript",
      "Tailwind CSS",
      "WordPress (ACF Pro)",
      "WooCommerce",
      "PHP",
      "Webpack / Vite",
    ],
  },
  {
    type: "education",
    title: "Organizacja i zarządzanie - studia menadżerskie",
    company: "Uniwersytet Ekonomiczny w Krakowie",
    period: "2020 - 2022",
    description:
      "Rozwinięcie kompetencji w zakresie zarządzania projektami, analizy procesów biznesowych oraz pracy zespołowej. Studia wzmocniły umiejętność komunikacji techniczno-biznesowej, planowania oraz podejmowania decyzji w środowisku projektowym.",
    technologies: [
      "Zarządzanie projektami",
      "Agile / Scrum",
      "Analiza procesów",
      "Komunikacja zespołowa",
      "Planowanie strategiczne",
    ],
  },
  {
    type: "education",
    title: "Finanse i rachunkowość",
    company: "Wyższa Szkoła Zarządzania i Bankowości w Krakowie",
    period: "2016 - 2020",
    description:
      "Silne podstawy analityczne, praca z danymi liczbowymi oraz myślenie systemowe. Studia rozwinęły umiejętność logicznego rozwiązywania problemów, analizowania złożonych procesów oraz dbałości o szczegóły — kluczowe w pracy z kodem i architekturą systemów.",
    technologies: [
      "Analiza danych",
      "Myślenie logiczne",
      "Modelowanie procesów",
      "Rozwiązywanie problemów",
    ],
  },
];

export const footerSocialLinks = [
  {
    icon: FaGithub,
    href: "https://github.com/AmandaChawinska",
    label: "GitHub",
  },
  {
    icon: FaLinkedinIn,
    href: "https://pl.linkedin.com/in/amanda-chawi%C5%84ska-frontend-developer",
    label: "LinkedIn",
  },
  { icon: Mail, href: "mailto:amanda.chawinska@spoko.pl", label: "Email" },
];

export const projects = [
  {
    title: "Willow",
    description:
      "Projekt strony internetowej w html i tailwind css na potrzeby zadania rekrutacyjnego.",
    image: "/images/willow.png",
    techStack: ["HTML", "Tailwind CSS", "Vite"],
    demoUrl: "",
    githubUrl: "https://github.com/AmandaChawinska/willow-vite-tw",
    tag: ["Wszystkie", "Vanilla JS / Frontend"],
  },
  {
    title: "Slaider",
    description:
      "Projekt slider napisany w języku Java Script z paginacją i automatycznym odtwarzaniem.",
    image: "/images/Slaider.png",
    techStack: ["HTML", "CSS", "Java Script"],
    demoUrl: "https://amandachawinska.github.io/slaider/",
    githubUrl: "https://github.com/AmandaChawinska/slaider",
    tag: ["Wszystkie", "Vanilla JS / Frontend"],
  },
  {
    title: "List task",
    description:
      "Prosty projekt listy zadań w Java Script. Możliwość dodawania, usuwania, odznaczania i ukrywania zadań.",
    image: "/images/list-task.png",
    techStack: ["HTML", "CSS", "Java script", "BEM convention"],
    demoUrl: "https://amandachawinska.github.io/List-task/",
    githubUrl: "https://github.com/AmandaChawinska/List-task",
    tag: ["Wszystkie", "Vanilla JS / Frontend"],
  },
  {
    title: "List task react",
    description:
      "Bardziej rozbudowana lista zadań oparta na React przy użyciu Redux, Redux-Saga i React-Router. Obejmuje wyszukiwanie, filtrowanie zadań, pobieranie przykładowych zadań i zapisywanie ich w pamięci lokalnej.",
    image: "/images/list-task-react.png",
    techStack: [
      "HTML",
      "Styled-components",
      "React",
      "React-redux",
      "React-saga",
      "React-router",
    ],
    demoUrl: "https://amandachawinska.github.io/List-task-react/#/zadania",
    githubUrl: "https://github.com/AmandaChawinska/List-task-react",
    tag: ["Wszystkie", "React/Next"],
  },
  {
    title: "Currency converter",
    description:
      "Strona zawiera formularz do przeliczania walut. Dostępne są wszystkie waluty Europejskiego Banku Centralnego.",
    image: "/images/currencyconverter.png",
    techStack: ["HTML", "styled-components", "React", "API"],
    demoUrl: "https://amandachawinska.github.io/currency-converter-in-React/",
    githubUrl: "https://github.com/AmandaChawinska/currency-converter-in-React",
    tag: ["Wszystkie", "React/Next"],
  },
  {
    title: "Movies browser",
    description:
      "Aplikacja do przeglądania i wyszukiwania filmów, aktorów i ekipy filmowej. Możliwość zmiany koloru tła i języka oraz szybki powrót na górę strony.",
    image: "/images/moviesbrowser.png",
    techStack: [
      "HTML",
      "styled-components",
      "React",
      "React-redux",
      "React-saga",
      "React-router",
    ],
    demoUrl: "https://wknott.github.io/movies-browser/#/movies",
    githubUrl: "https://github.com/wknott/movies-browser",
    tag: ["Wszystkie", "React/Next"],
  },
  {
    title: "One page - Eurocash",
    description: "Prosta strona typu one-page z linkiem do pobrania aplikacji.",
    image: "/images/eurocash.png",
    techStack: ["HTML", "CSS"],
    demoUrl: "https://www.grupaeurocash.pl/aplikacja",
    githubUrl: "",
    tag: ["Wszystkie", "Vanilla JS"],
  },
  {
    title: "Frostpunk2",
    description:
      "Strona promująca grę komputerową, stworzona z użyciem WordPress i Bootstrap 5.",
    image: "/images/frostpunk2.png",
    techStack: [
      "HTML",
      "CSS",
      "Bootstrap 5",
      "PHP",
      "WordPress",
      "ACF Pro",
      "JavaScript",
    ],
    demoUrl: "https://frostpunk2.com/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Lerg",
    description:
      "Strona produktowa z blogiem, przygotowana w WordPress. Przejęta w początkowej fazie projektu.",
    image: "/images/lerg.png",
    techStack: [
      "HTML",
      "CSS",
      "Bootstrap 5",
      "WordPress",
      "PHP",
      "ACF Pro",
      "JavaScript",
    ],
    demoUrl: "https://www.lerg.pl/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Czas na młodych",
    description:
      "Rozbudowana strona z wieloma taksonomiami i panelem administracyjnym. Odpowiedzialność za frontend.",
    image: "/images/czasnamlodych.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "WordPress",
      "PHP",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://terazmy.eu/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Apetigo - landing page",
    description:
      "Landing page dla Apetigo, zoptymalizowany pod responsywność i prostą nawigację.",
    image: "/images/apetigo-landingpage.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "WordPress",
      "PHP",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://apetigo.pl",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "QR Apetigo",
    description: "Strona WordPress z animacjami i formularzem kontaktowym.",
    image: "/images/apetigo.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "WordPress",
      "PHP",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://qr.apetigo.pl/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Apetigo - tips",
    description: "One-page z informacjami dotyczącymi tippingu.",
    image: "/images/apetigo-tips.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "WordPress",
      "PHP",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://tips.apetigo.pl/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Balt-invest",
    description:
      "Strona nieruchomości w dwóch językach, przygotowana w WordPress.",
    image: "/images/baltinvest.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "WordPress",
      "PHP",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://baltinvest.pl",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "KNHP",
    description:
      "Strona prezentująca inicjatywy i działania organizacji Kraków Nowa Huta Przyszłości S.A. Odpowiadałam za frontend: implementację UI, strukturę sekcji i integrację komponentów w zespole projektowym.",
    image: "/images/knhp.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "PHP",
      "WordPress",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://knhp.com.pl/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Porfolio",
    description:
      "Moje osobiste portfolio zbudowane w Next.js 16, React 19 i TypeScript 5, prezentujące projekty oraz umiejętności frontendowe. Zawiera gotowe komponenty UI, animacje i tryb ciemny. Strona jest responsywna i zoptymalizowana pod kątem wydajności.",
    image: "/images/portfolio.png",
    techStack: [
      "HTML",
      "Tailwind CSS",
      "React",
      "JavaScript/TypeScript",
      "Next.js",
      "React Hook Form",
      "Resend",
      "Shadcn",
      "next-themes",
      "aos",
    ],
    demoUrl: "",
    githubUrl: "",
    tag: ["Wszystkie", "React/Next"],
  },
  {
    title: "SEDG",
    description:
      "Strona prezentująca projekty domów, producentów i materiały. Przejęta po innym programiście. Odpowiedzialność za poprawki i dodawanie nowych funkcjonalności.",
    image: "/images/sedg.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "WordPress",
      "PHP",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://sedg.pl",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Express okna",
    description:
      "Strona dla klienta z branży stolarki PCV i aluminium. Rozbudowana o taksonomie produktów i intuicyjny system prezentacji oferty.",
    image: "/images/expresokna.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "PHP",
      "WordPress",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://expresokna.pl/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Top garaze",
    description:
      "Strona dla klienta z branży konstrukcji stalowych występująca w kilku wersjach językowych.",
    image: "/images/topgaraze.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "WordPress",
      "PHP",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://topgaraze.pl",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Office angels",
    description: "Ciekawa kolorystycznie strona z licznymi grafikami.",
    image: "/images/officeangels.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "PHP",
      "WordPress",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://officeangels.pl/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Mystery machinery",
    description:
      "W tym projekcie byłam odpowiedzialna za implementacje zmiany języka + tłumaczenia. Napisałam też wtyczkę newsletter zsynchronizowaną z contact form 7, która wysyła dane do panelu admina.",
    image: "/images/mystery.png",
    techStack: [
      "HTML",
      "CSS",
      "Scss",
      "WordPress",
      "PHP",
      "ACF Pro",
      "JavaScript",
    ],
    demoUrl: "https://mysterymachinery.pl",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Omegadruk",
    description:
      "Strona prezentująca ofertę firmy z branży druku. Zbudowana w WordPress z użyciem ACF Pro.",
    image: "/images/omegadruk.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "PHP",
      "WordPress",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: " https://omegadruk-dev.devheron.pl",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "11 bits",
    description: "Strona korporacyjna dla studia deweloperskiego.",
    image: "/images/11bits.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "PHP",
      "WordPress",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://ir.11bitstudios.com/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Love brands",
    description:
      "Strona przerobiona wg. pomysłu klienta na gotowym szablonie WordPress. ",
    image: "/images/lovebrands.png",
    techStack: ["HTML", "CSS", "WordPress", "JavaScript"],
    demoUrl: "https://lovebrandsgroup.pl/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "GQB",
    description:
      "Strona z produktami odzieżowymi z rozbudowaną hierarchią kategorii i filtrów. Zbudowana w WordPress z użyciem ACF Pro i WooCommerce. Przygotowana pod SEO",
    image: "/images/gqb.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "WordPress",
      "PHP",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
      "WooCommerce",
      "SEO",
    ],
    demoUrl: "https://gqb.pl/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Sopoltrad",
    description:
      "Zmodyfikowana strona wg. pomysłu klienta na gotowym szablonie WordPress.",
    image: "/images/sopoltrad.png",
    techStack: ["HTML", "CSS", "WordPress", "ACF Pro", "JavaScript"],
    demoUrl: "https://sopoltrad.com/pl/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "MobileMed",
    description:
      "Strona dla klienta z branży medycznej, zbudowana w WordPress z użyciem ACF Pro z interaktywną mapą i blogiem",
    image: "/images/mobilemed.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "PHP",
      "WordPress",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://www.mobilemed.pl",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Osnova",
    description:
      "Strona dla klienta z branży nieruchomości, odświeżona i przebudowana na nowy design z filtrami wyboru mieszkania.",
    image: "/images/osnova.png",
    techStack: ["HTML", "CSS", "PHP", "WordPress", "ACF Pro", "JavaScript"],
    demoUrl: "https://osnova.devheron.pl/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Krakzal",
    description:
      "Strona dla producena osłon okiennych wytwarzanych na miarę. Zbudowana w WordPress z użyciem ACF Pro i Tailwind CSS.",
    image: "/images/krakzal.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "PHP",
      "WordPress",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
    ],
    demoUrl: "https://krakzal.devheron.pl",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "Sni",
    description:
      "Responsywna strona firmowa prezentująca ofertę usług i kompetencje SNI Consulting. Odpowiadałam za implementację frontendu i warstwy wizualnej zgodnie z projektem. Strona posiada różne animacje, zaawansowaną wyszukiwarkę ofert, dodano też funkcjonalności do admina tj. np wyszukiwanie w postach po polu, które domyślnie nie występuje.",
    image: "/images/sni.png",
    techStack: [
      "HTML",
      "CSS",
      "Tailwind CSS",
      "WordPress",
      "PHP",
      "ACF Pro",
      "JavaScript",
      "Alpine.js",
      "Animation",
    ],
    demoUrl: "https://www.sniconsulting.net/",
    githubUrl: "",
    tag: ["Wszystkie", "WordPress"],
  },
  {
    title: "API OpenAI",
    description:
      "Aplikacja pobiera artykuł tekstowy z zewnętrznego adresu URL, a następnie przetwarza go za pomocą OpenAI (model GPT-3.5) w celu konwersji na kod HTML. Wygenerowany kod HTML jest zapisywany w pliku artykul.html, a następnie aplikacja tworzy podstawowy szablon HTML, który zawiera odpowiednie nagłówki, style CSS (używając Tailwind CSS) i miejsce na wstawienie treści artykułu. Ten szablon jest zapisywany w pliku szablon.html. Następnym krokiem jest wygenerowanie podglądu artykułu, który wstawia wygenerowany kod HTML do szablonu, a wynikowy plik jest zapisywany jako podglad.html. Na koniec aplikacja wyświetla komunikaty o powodzeniu lub błędach podczas tych operacji. Celem aplikacji jest automatyczne pobieranie artykułów, konwertowanie ich na semantyczny kod HTML oraz generowanie szablonów i podglądów gotowych dokumentów.",
    image: "/images/project.png",
    techStack: ["HTML", "CSS", "Tailwind CSS", "JavaScript", "Node.js"],
    demoUrl: "",
    githubUrl: "https://github.com/AmandaChawinska/API-Open-AI",
    tag: ["Wszystkie", "Vanilla JS / Frontend"],
  },
  {
    title: "Rock paper scissors",
    description: "Zadanie z frontend mentor.",
    image: "/images/project.png",
    techStack: ["HTML", "CSS", "JavaScript"],
    demoUrl: "",
    githubUrl: "https://github.com/AmandaChawinska/rock-paper-scissors",
    tag: ["Wszystkie", "Vanilla JS / Frontend"],
  },
  {
    title: "REST Countries API",
    description: "Zadanie z frontend mentor.",
    image: "/images/project.png",
    techStack: ["HTML", "CSS", "JavaScript", "API"],
    demoUrl: "",
    githubUrl:
      "https://github.com/AmandaChawinska/REST-Countries-API---frontend-mentor",
    tag: ["Wszystkie", "Vanilla JS / Frontend"],
  },
  {
    title: "Tag browser",
    description:
      "Aplikacja służy do pobierania tagów z API Stack Exchange. Wysyła nazwę w tabeli składającej się z dwóch kolumn. W pierwszej kolumnie pobiera nazwy tagów, a w drugiej liczbę powiązanych wpisów. Możesz wybrać liczbę wyświetlanych elementów, sortować według najpopularniejszych lub nazw, a także zmienić kierunek sortowania. Aplikacja oferuje również podstawową paginację z nazwą aktualnie wyświetlanej strony i liczbą wyświetlanych elementów.",
    image: "/images/project.png",
    techStack: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "React Query",
      "MUI",
      "Storybook",
      "API",
    ],
    demoUrl: "https://tag-browser.netlify.app/",
    githubUrl: "https://github.com/AmandaChawinska/tag-browser",
    tag: ["Wszystkie", "React/Next"],
  },
  {
    title: "Note App",
    description:
      "Aplikacja służy do tworzenia, usuwania, edytowania i archiwizowania notatek.",
    image: "/images/project.png",
    techStack: ["HTML", "CSS Modules", "JavaScript", "React", "React Router"],
    demoUrl: "",
    githubUrl: "https://github.com/AmandaChawinska/note-App",
    tag: ["Wszystkie", "React/Next"],
  },
];

export const skillCategories = [
  {
    title: "Frontend",
    skills: [
      { name: "JavaScript (ES6+)", icon: Code2 },
      { name: "TypeScript", icon: Terminal },
      { name: "React (Hooks, Query, Hook Form)", icon: Code2 },
      { name: "Next.js (projekty własne)", icon: Globe },
      { name: "Alpine.js", icon: Layout },
      { name: "HTML5 (semantic & accessibility)", icon: Code2 },
      { name: "Tailwind CSS", icon: Palette },
      { name: "Styled Components / CSS Modules", icon: Palette },
      { name: "Responsive Web Design", icon: Smartphone },
    ],
  },
  {
    title: "CMS/Backend",
    skills: [
      { name: "WordPress (custom themes, ACF Pro)", icon: Server },
      { name: "WooCommerce", icon: Server },
      { name: "PHP (WordPress context)", icon: Terminal },
      { name: "Integracja REST API", icon: Cloud },
    ],
  },
  {
    title: "Narzędzia i workflow",
    skills: [
      { name: "Git", icon: GitBranch },
      { name: "Webpack / Vite", icon: Cpu },
      { name: "Figma / Adobe XD", icon: Palette },
      { name: "AI-assisted development", icon: Cpu },
      { name: "Praca zespołowa (Scrum, Trello, ActiveCollab)", icon: Layers },
    ],
  },
];
